# Site settings
title:Florence09.github.io
email: 
description:技术分享博客
  Jekyll Theme Demo
baseurl:''
url: http://Florence09.github.io

github_username:Florence09

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
